//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.WCFProductos {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/_100DaysOfCode_WCF")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private string codigoField;
        
        private int idField;
        
        private byte[] imagenField;
        
        private string nombreField;
        
        private double precioField;
        
        private string rutaImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoField, value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] imagen {
            get {
                return this.imagenField;
            }
            set {
                if ((object.ReferenceEquals(this.imagenField, value) != true)) {
                    this.imagenField = value;
                    this.RaisePropertyChanged("imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rutaImagen {
            get {
                return this.rutaImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.rutaImagenField, value) != true)) {
                    this.rutaImagenField = value;
                    this.RaisePropertyChanged("rutaImagen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFProductos.IWCFProducto")]
    public interface IWCFProducto {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFProducto/BuscarProductos", ReplyAction="http://tempuri.org/IWCFProducto/BuscarProductosResponse")]
        System.IAsyncResult BeginBuscarProductos(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto> EndBuscarProductos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFProducto/AgregarProducto", ReplyAction="http://tempuri.org/IWCFProducto/AgregarProductoResponse")]
        System.IAsyncResult BeginAgregarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState);
        
        string EndAgregarProducto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFProducto/ModificarProducto", ReplyAction="http://tempuri.org/IWCFProducto/ModificarProductoResponse")]
        System.IAsyncResult BeginModificarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState);
        
        string EndModificarProducto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWCFProducto/EliminarProducto", ReplyAction="http://tempuri.org/IWCFProducto/EliminarProductoResponse")]
        System.IAsyncResult BeginEliminarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState);
        
        string EndEliminarProducto(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFProductoChannel : WebService.WCFProductos.IWCFProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuscarProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public BuscarProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AgregarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ModificarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFProductoClient : System.ServiceModel.ClientBase<WebService.WCFProductos.IWCFProducto>, WebService.WCFProductos.IWCFProducto {
        
        private BeginOperationDelegate onBeginBuscarProductosDelegate;
        
        private EndOperationDelegate onEndBuscarProductosDelegate;
        
        private System.Threading.SendOrPostCallback onBuscarProductosCompletedDelegate;
        
        private BeginOperationDelegate onBeginAgregarProductoDelegate;
        
        private EndOperationDelegate onEndAgregarProductoDelegate;
        
        private System.Threading.SendOrPostCallback onAgregarProductoCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarProductoDelegate;
        
        private EndOperationDelegate onEndModificarProductoDelegate;
        
        private System.Threading.SendOrPostCallback onModificarProductoCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarProductoDelegate;
        
        private EndOperationDelegate onEndEliminarProductoDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarProductoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFProductoClient() : 
                base(WCFProductoClient.GetDefaultBinding(), WCFProductoClient.GetDefaultEndpointAddress()) {
        }
        
        public WCFProductoClient(EndpointConfiguration endpointConfiguration) : 
                base(WCFProductoClient.GetBindingForEndpoint(endpointConfiguration), WCFProductoClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public WCFProductoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WCFProductoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public WCFProductoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WCFProductoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public WCFProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<BuscarProductosCompletedEventArgs> BuscarProductosCompleted;
        
        public event System.EventHandler<AgregarProductoCompletedEventArgs> AgregarProductoCompleted;
        
        public event System.EventHandler<ModificarProductoCompletedEventArgs> ModificarProductoCompleted;
        
        public event System.EventHandler<EliminarProductoCompletedEventArgs> EliminarProductoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebService.WCFProductos.IWCFProducto.BeginBuscarProductos(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBuscarProductos(oProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto> WebService.WCFProductos.IWCFProducto.EndBuscarProductos(System.IAsyncResult result) {
            return base.Channel.EndBuscarProductos(result);
        }
        
        private System.IAsyncResult OnBeginBuscarProductos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WebService.WCFProductos.Producto oProducto = ((WebService.WCFProductos.Producto)(inValues[0]));
            return ((WebService.WCFProductos.IWCFProducto)(this)).BeginBuscarProductos(oProducto, callback, asyncState);
        }
        
        private object[] OnEndBuscarProductos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto> retVal = ((WebService.WCFProductos.IWCFProducto)(this)).EndBuscarProductos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnBuscarProductosCompleted(object state) {
            if ((this.BuscarProductosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BuscarProductosCompleted(this, new BuscarProductosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BuscarProductosAsync(WebService.WCFProductos.Producto oProducto) {
            this.BuscarProductosAsync(oProducto, null);
        }
        
        public void BuscarProductosAsync(WebService.WCFProductos.Producto oProducto, object userState) {
            if ((this.onBeginBuscarProductosDelegate == null)) {
                this.onBeginBuscarProductosDelegate = new BeginOperationDelegate(this.OnBeginBuscarProductos);
            }
            if ((this.onEndBuscarProductosDelegate == null)) {
                this.onEndBuscarProductosDelegate = new EndOperationDelegate(this.OnEndBuscarProductos);
            }
            if ((this.onBuscarProductosCompletedDelegate == null)) {
                this.onBuscarProductosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBuscarProductosCompleted);
            }
            base.InvokeAsync(this.onBeginBuscarProductosDelegate, new object[] {
                        oProducto}, this.onEndBuscarProductosDelegate, this.onBuscarProductosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebService.WCFProductos.IWCFProducto.BeginAgregarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAgregarProducto(oProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WebService.WCFProductos.IWCFProducto.EndAgregarProducto(System.IAsyncResult result) {
            return base.Channel.EndAgregarProducto(result);
        }
        
        private System.IAsyncResult OnBeginAgregarProducto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WebService.WCFProductos.Producto oProducto = ((WebService.WCFProductos.Producto)(inValues[0]));
            return ((WebService.WCFProductos.IWCFProducto)(this)).BeginAgregarProducto(oProducto, callback, asyncState);
        }
        
        private object[] OnEndAgregarProducto(System.IAsyncResult result) {
            string retVal = ((WebService.WCFProductos.IWCFProducto)(this)).EndAgregarProducto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAgregarProductoCompleted(object state) {
            if ((this.AgregarProductoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AgregarProductoCompleted(this, new AgregarProductoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AgregarProductoAsync(WebService.WCFProductos.Producto oProducto) {
            this.AgregarProductoAsync(oProducto, null);
        }
        
        public void AgregarProductoAsync(WebService.WCFProductos.Producto oProducto, object userState) {
            if ((this.onBeginAgregarProductoDelegate == null)) {
                this.onBeginAgregarProductoDelegate = new BeginOperationDelegate(this.OnBeginAgregarProducto);
            }
            if ((this.onEndAgregarProductoDelegate == null)) {
                this.onEndAgregarProductoDelegate = new EndOperationDelegate(this.OnEndAgregarProducto);
            }
            if ((this.onAgregarProductoCompletedDelegate == null)) {
                this.onAgregarProductoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgregarProductoCompleted);
            }
            base.InvokeAsync(this.onBeginAgregarProductoDelegate, new object[] {
                        oProducto}, this.onEndAgregarProductoDelegate, this.onAgregarProductoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebService.WCFProductos.IWCFProducto.BeginModificarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarProducto(oProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WebService.WCFProductos.IWCFProducto.EndModificarProducto(System.IAsyncResult result) {
            return base.Channel.EndModificarProducto(result);
        }
        
        private System.IAsyncResult OnBeginModificarProducto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WebService.WCFProductos.Producto oProducto = ((WebService.WCFProductos.Producto)(inValues[0]));
            return ((WebService.WCFProductos.IWCFProducto)(this)).BeginModificarProducto(oProducto, callback, asyncState);
        }
        
        private object[] OnEndModificarProducto(System.IAsyncResult result) {
            string retVal = ((WebService.WCFProductos.IWCFProducto)(this)).EndModificarProducto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificarProductoCompleted(object state) {
            if ((this.ModificarProductoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarProductoCompleted(this, new ModificarProductoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarProductoAsync(WebService.WCFProductos.Producto oProducto) {
            this.ModificarProductoAsync(oProducto, null);
        }
        
        public void ModificarProductoAsync(WebService.WCFProductos.Producto oProducto, object userState) {
            if ((this.onBeginModificarProductoDelegate == null)) {
                this.onBeginModificarProductoDelegate = new BeginOperationDelegate(this.OnBeginModificarProducto);
            }
            if ((this.onEndModificarProductoDelegate == null)) {
                this.onEndModificarProductoDelegate = new EndOperationDelegate(this.OnEndModificarProducto);
            }
            if ((this.onModificarProductoCompletedDelegate == null)) {
                this.onModificarProductoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarProductoCompleted);
            }
            base.InvokeAsync(this.onBeginModificarProductoDelegate, new object[] {
                        oProducto}, this.onEndModificarProductoDelegate, this.onModificarProductoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WebService.WCFProductos.IWCFProducto.BeginEliminarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarProducto(oProducto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WebService.WCFProductos.IWCFProducto.EndEliminarProducto(System.IAsyncResult result) {
            return base.Channel.EndEliminarProducto(result);
        }
        
        private System.IAsyncResult OnBeginEliminarProducto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WebService.WCFProductos.Producto oProducto = ((WebService.WCFProductos.Producto)(inValues[0]));
            return ((WebService.WCFProductos.IWCFProducto)(this)).BeginEliminarProducto(oProducto, callback, asyncState);
        }
        
        private object[] OnEndEliminarProducto(System.IAsyncResult result) {
            string retVal = ((WebService.WCFProductos.IWCFProducto)(this)).EndEliminarProducto(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEliminarProductoCompleted(object state) {
            if ((this.EliminarProductoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarProductoCompleted(this, new EliminarProductoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarProductoAsync(WebService.WCFProductos.Producto oProducto) {
            this.EliminarProductoAsync(oProducto, null);
        }
        
        public void EliminarProductoAsync(WebService.WCFProductos.Producto oProducto, object userState) {
            if ((this.onBeginEliminarProductoDelegate == null)) {
                this.onBeginEliminarProductoDelegate = new BeginOperationDelegate(this.OnBeginEliminarProducto);
            }
            if ((this.onEndEliminarProductoDelegate == null)) {
                this.onEndEliminarProductoDelegate = new EndOperationDelegate(this.OnEndEliminarProducto);
            }
            if ((this.onEliminarProductoCompletedDelegate == null)) {
                this.onEliminarProductoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarProductoCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarProductoDelegate, new object[] {
                        oProducto}, this.onEndEliminarProductoDelegate, this.onEliminarProductoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WebService.WCFProductos.IWCFProducto CreateChannel() {
            return new WCFProductoClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFProducto)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWCFProducto)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:50170/WCFProducto.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return WCFProductoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWCFProducto);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return WCFProductoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWCFProducto);
        }
        
        private class WCFProductoClientChannel : ChannelBase<WebService.WCFProductos.IWCFProducto>, WebService.WCFProductos.IWCFProducto {
            
            public WCFProductoClientChannel(System.ServiceModel.ClientBase<WebService.WCFProductos.IWCFProducto> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginBuscarProductos(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oProducto;
                System.IAsyncResult _result = base.BeginInvoke("BuscarProductos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto> EndBuscarProductos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto> _result = ((System.Collections.ObjectModel.ObservableCollection<WebService.WCFProductos.Producto>)(base.EndInvoke("BuscarProductos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAgregarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oProducto;
                System.IAsyncResult _result = base.BeginInvoke("AgregarProducto", _args, callback, asyncState);
                return _result;
            }
            
            public string EndAgregarProducto(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("AgregarProducto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oProducto;
                System.IAsyncResult _result = base.BeginInvoke("ModificarProducto", _args, callback, asyncState);
                return _result;
            }
            
            public string EndModificarProducto(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ModificarProducto", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEliminarProducto(WebService.WCFProductos.Producto oProducto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oProducto;
                System.IAsyncResult _result = base.BeginInvoke("EliminarProducto", _args, callback, asyncState);
                return _result;
            }
            
            public string EndEliminarProducto(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("EliminarProducto", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IWCFProducto,
        }
    }
}
